### ISSUE TITLE
前後台的程式串接原則

### ISSUE THREAD

**Issue by fychao** [fychao/CYU-BigData-2018#5]
- 設計資料互通的架構

**Comment by chen11223344** [comment]
![36119936-7c6f-4c28-9332-31b69163a96a](https://user-images.githubusercontent.com/45503484/49323967-6598a180-f55f-11e8-8b62-e5377fa53c72.jpeg)

1.將5張like/dislike輸出結果送到後台
2.將結果變成詞向量(取like/dislike內容)
3.將詞向量進行cos  (like dislike都要)(dislike結果不採用)

**Comment by 10796501** [comment]
1.將5張like/dislike結果送到後台
2.使用者結果丟後台
3.選完後
4.依使用者like/dislike結果 將step1字詞分成like/dislike的文字內容 送到後台做分詞 TFIDF COSine
